### ISSUE TITLE
Check local repo. status before push: all changes should be committed

### ISSUE THREAD

**Issue by c-fabre** [open-src-soc/website#10]
Similar to #8: The Makefile ought to check that the local repo. is clean with all files committed before succeeding a "make push."

**Comment by damiencourousse** [comment]
Stp peux-tu préciser ton besoin.  je vois au moins deux possibilités :
- abort s'il y a des fichiers qui ne sont pas committés (`Untracked files`)
- abort s'il y a des fichiers avec des changements qui ne sont pas committés (`Changes not staged`).

**Comment by damiencourousse** [comment]
closed by mistake

**Comment by damiencourousse** [comment]
Added in 0aafa21: now cleaning repo's contents with `stash`.
