### ISSUE TITLE
Re-use of gdr-scienday-program.org in different context makes a link to speaker list awkward.

### ISSUE THREAD

**Issue by sefau** [open-src-soc/website#11]
In commit f5d2710f2ba0c6d532516bacefcab8e53f0bd1e7, pages for individual events have been added. These pages re-use the already existing pages describing the program and the speakers of each event.

In gdr-scienday-program.org, a link is given to the speaker page. This link is awkward in the gdr-scienday.org since the list of speaker is given on the very same page. 

Possible fix: if the full program pages is removed then the link can be removed. Otherwise, a new pages should be created, without the link, to build the gdr-sicenday.org page.

**Comment by c-fabre** [comment]
Wow... Conditional hyperlinks would be needed :-(
I will most likely remove the "all speakers" page, and append the speakers to the program for individual eventsas well as for the week as a whole. This will fix it.
I wont do before new week I guess, though...
