### ISSUE TITLE
The "=" in "mailto:foo@example.com?subject=Whatever" URL shall not be escaped

### ISSUE THREAD

**Issue by c-fabre** [open-src-soc/website#2]
The process that escapes characters in mailto URLs should be more careful: In the "=" that follows a field name should be left as is.

**Comment by damiencourousse** [comment]
je n'arrive pas à reproduire ton problème.
stp as-tu un exemple minimaliste ?

**Comment by c-fabre** [comment]
Wait... Il semble que le bug soit dans le mode ORG de emacs, qui reecrit les URL sans faire attention aux particularités des URL en "mailto:"

**Comment by c-fabre** [comment]
C. f. la ligne 33 de "pages/sponsors.org", qui me posait problème.

**Comment by c-fabre** [comment]
Le bug étant dans emacs, ce dépôt n'est pas concerné.
Le workaround à grand coups de "sed" reste en place, cependant.
