### ISSUE TITLE
Issues with includes in ORG files with Pandoc

### ISSUE THREAD

**Issue by c-fabre** [open-src-soc/website#3]
PanDoc does not process the "#+INCLUDE:" directives for ORG files when generating HTML.
Exporting HTML from Emacs seems too work though...
Check for instance the three includes in file "pages/programme.org" in branch "site-spliting"

**Comment by c-fabre** [comment]
According to [https://github.com/jgm/pandoc/issues/3510](https://github.com/jgm/pandoc/issues/3510) this should be fixed in PanDoc 2.0. We are using 2.2.x...

**Comment by damiencourousse** [comment]
Warning.  Commit 4dda070 supports `#+include:` org directives, but hakyll does not detect changes to the target includes.  i.e. you need to use `make rebuild` to make sure that everything was properly generated.

I would prefer reverting 4dda070, and not supporting this feature.

**Comment by c-fabre** [comment]
Please don't revert: I do need includes for now!
