### ISSUE TITLE
make push fails to merge site

### ISSUE THREAD

**Issue by sefau** [open-src-soc/website#4]
When calling make push, I encounter the following error during the commit of site:

```
cd site \
        && git checkout master \
        && git add . \
        && git commit -m 'site update' \
        && git push origin master
error: Vos modifications locales aux fichiers suivants seraient écrasées par l'extraction :
        sitemap.xml

```

Output of `cd site && git diff sitemap.xml ` is given in the attached file. 

[diff.log](https://github.com/open-src-soc/website/files/3457204/diff.log)

**Comment by damiencourousse** [comment]
> Le 1 août 2019 à 16:30, sefau <notifications@github.com> a écrit :
> 
> When calling make push, I encounter the following error during the commit of site:
> 
> cd site \
>         && git checkout master \
>         && git add . \
>         && git commit -m 'site update' \
>         && git push origin master
> error: Vos modifications locales aux fichiers suivants seraient écrasées par l'extraction :
>         sitemap.xml
> 

Mon hypothèse est que le git checkout ne passe pas parce qu’il y a des modifications locales dans le sous-module ´site’.  

cd site && git pull 
résoudront probablement le problème.

>

**Comment by sefau** [comment]
Non, les modifs dans site sont uniquement celles créées par pandoc lors de la compilation. Ce qui lui pose problème semble être le timestamp des fichiers modifiés dans sitemap.xml.

cd site && git pull me donne :

```
Vous n'êtes actuellement sur aucune branche.
Veuillez spécifier une branche avec laquelle fusionner.
Référez-vous à git-pull(1) pour de plus amples détails.

    git pull <distant> <branche>
```
Et cd site && git branch me donne :

```
* (HEAD détachée depuis 58e67fd)
  master
```

Ma connaissance de git est assez limitée, j'ai peut être fait une mauvaise manip mais de mémoire, en dehors des commit des fichiers org, je n'ai utilisé que le makefile pour les push/pull.

**Comment by damiencourousse** [comment]
cd site
git reset —hard
git checkout master
git pull

**Comment by sefau** [comment]
Problem résolu, merci.

**Comment by damiencourousse** [comment]
Impec’ !

**Comment by sefau** [comment]
I have the same problem again. I can repeat the solution but I do not understand why it happens. In the meantime, I do not push to avoid breaking anything.

**Comment by damiencourousse** [comment]
> I have the same problem again. I can repeat the solution but I do not understand why it happens. In the meantime, I do not push to avoid breaking anything.

I need more information to provide help.

**Comment by sefau** [comment]
I followed the techniques used last time and it solved the problem. 

I don't know why it creates conflicts in the site submodule. Once all modifications are in commit I just `make pull` then `make push`.

**Comment by sefau** [comment]
Well, the same issues strikes back and the former solution does not solve it this time. I could solve the conflict by hand in the html files and commit the result but I'm not sure that it is the expected approach. 
What type of information could I provide to help understanding the problem?

Here is the current state as reported when using make pull:

```
git pull --recurse-submodules
Fetching submodule site
Déjà à jour.
gdr-scienday.html: needs merge
program.html: needs merge
error: vous devez d'abord résoudre votre index courant
Impossible d'extraire 'bfdb55ebe11a323137d10dc511a1a93dec12a09b' dans le chemin de sous-module 'site'
make: *** [Makefile:15: pull] Error 1
```
