### ISSUE TITLE
ORG paragraphs in /italics/ not passed on to HTML

### ISSUE THREAD

**Issue by c-fabre** [open-src-soc/website#7]
In the branch "week-split" on the page speakers, there are several multi-lines paragraphs (short bio.) that are enclosed by // and should be formatted as italics, but are not.

**Comment by c-fabre** [comment]
Seems to work for a couple of words, but not for several lines.

**Comment by sefau** [comment]
It seems to be the expected behaviour, see for instance [[https://emacs.stackexchange.com/questions/27892/italic-paragraphs-in-org-mode]]

A possible workaround is ti "join" the lines of the paragraph (and then use something like global-visual-line in emacs to have a readable display).

**Comment by damiencourousse** [comment]
By default,  org-mode supports 1 newline maximum in an emphasis expression.

The change required by this feature wish is probably too invasive; it would require to modify the emacs/org-mode variable `org-emphasis-regexp-components`; which would probably require to embed an emacs context in the hakyll build process.

wontfix
